# fly.toml app configuration file generated for libretranslate-crimson-glade-7693 on 2025-04-23T18:15:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'libretranslate-crimson-glade-7693'
primary_region = 'mad'

[build]
  image = 'libretranslate/libretranslate:latest'

[env]
  LT_LOAD_ONLY = 'en,es'

[http_service]
  internal_port = 5000
  #auto_stop_machines = 'stop'
  #auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-4x'
  memory = '4096mb'
# top1.nearest.of.libretranslate-crimson-glade-7693.internal